### PR TITLE
Dockerization

### PR DESCRIPTION
**Pull request by nonnib**
Removing celery
Refactoring logging to conform with docker best practices. No longer split up logs by type and output standardized logstash json to stdout. Allow `LOG_FORMAT=text` app config override for local development.
Setting up deployment pipeline to pypi same as drift-config. Version is maintained in git tags.

### CODE REVIEW

**Comment by judgeaxl** [comment]
I get an error when setting up the dev environment:

`pip install -e "../drift[aws,test]" `

ERROR: flask-smorest 0.21.0 has requirement webargs>=6.0.0, but you'll have webargs 5.5.3 which is incompatible.

**Comment by judgeaxl** [comment]
```
export FLASK_APP=drift.devapplocal:app
flask run
```
fails:
 * Serving Flask app "drift.devapplocal:app"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Usage: flask run [OPTIONS]

Error: Could not import "drift.devapplocal".

**Comment by judgeaxl** [comment]
It think it would be good if build and push were separate commands, as one might want to run local tests without having to publish the image to docker every time. Also, since this is a public project that tries to publish to our private docker repo, it's an odd setup.

**Comment by nonnib** [comment]
https://github.com/dgnorth/drift/pull/13#issuecomment-632481409
Not sure what the problem is here. Try uninstalling webargs or refreshing your virtualenv?

**Comment by nonnib** [comment]
https://github.com/dgnorth/drift/pull/13#issuecomment-632482619
I don't see a devapplocal in drift.

**Comment by nonnib** [comment]
> It think it would be good if build and push were separate commands, as one might want to run local tests without having to publish the image to docker every time. Also, since this is a public project that tries to publish to our private docker repo, it's an odd setup.

You are referring to drift-base? I'll split the steps into two. The docker repo is public I think.

**Comment by judgeaxl** [comment]
OK, the install error was due to the insane setup of installing `drift` from the sibling folder instead of from a defined GitHub release. Syncing the other repo to the right branch fixes it. This something that really should be sorted so it can be used reliably

**Pull request merged**
